### ISSUE TITLE
style guide

### ISSUE THREAD

**Issue by martyall** [f-o-a-m/kepler#10]
we should make a bare bones style guide to include basic rules on indentations because not all of this is controlled by stylish haskell. It should just be a markdown file with headers and examples

**Comment by martyall** [comment]
- [x] data definitions with records (including sum types)
- [x] constructors applied to records
- [x] where clauses 
- [x] function signatures
- [x] class instances

**Comment by safareli** [comment]
# Moved to wiki

https://github.com/f-o-a-m/hs-abci-server/wiki/code-style-guide

**Comment by martyall** [comment]
🎉

**Comment by martyall** [comment]
we can put this in the wiki maybe ?
