### ISSUE TITLE
Give description of how `storeKey` is actually used, and it's effect on grpc

### ISSUE THREAD

**Issue by martyall** [f-o-a-m/kepler#103]
- what is the storeKey actually doing?
- do we have to worry about how it effects gRPC interface?
- when a new KVStore is created for a module keeper, what happens?

**Comment by charlescrain** [comment]
Still working on this but this is my current iteration:

-----------------------------------------------------

### what is the storeKey actually doing?

~~It is used as the key to get the root of the store for the module. It seems there is nothing that prevents 2 modules having the same key. I'm not sure what would happen in this case so more research is required.~~

The `storeKey` is used to quickly look up the store for a module. The `MultiStore` that exists on the `context` of the sdk has a mapping of `storeKey` to `Store`. Each module's `store` has underlying prefixing of all keys using the `storeKey`. This is purely for convenience.

### do we have to worry about how it effects gRPC interface?

~~Yes. Right now it depends on what functions are provided via gRPC. The cosmos-sdk uses Tree abstractions for `Get` and `Set` when using `iavl`. cosmos-sdk builds a tree with the root and performs set/get via the tree which essentially acts as a KVStore. If the gRPC provides this abstraction in the interface then we should be good to go. Might be worth having a quick conversation around this.~~
No. The store key is just used for prefixing keys. `iavl` should be fine. 

### when a new KVStore is created for a module keeper, what happens?

~~It makes a sub kvstore that is treated as a normal kvstore but is somehow namespaced by the `storeKey`. I'm still working on understanding how it does this. It seems eerily similar to how the `iavl` implementation is done but doesn't use a tree abstraction, not sure why.~~

The KVStore for a module is just the regular KVStore but all `get/set`s have a hidden prefixing using the `storeKey`.

**Comment by martyall** [comment]
@charlescrain were you invited to the tendermint slack? If you have enough information to ask questions it might be worth taking it there, they usually respond quickly

**Comment by charlescrain** [comment]
@blinky3713 good call! I'll see if I have the invite.

**Comment by charlescrain** [comment]
@blinky3713 updated my comments. basically all says the same thing. We just need to handle the prefixing and we should be chill.

**Comment by martyall** [comment]
awesome thanks for that
