### ISSUE TITLE
write hook for message validation in module's router

### ISSUE THREAD

**Issue by martyall** [f-o-a-m/kepler#110]
Right now we have instance for validating messages , for example [here](https://github.com/f-o-a-m/hs-abci/blob/master/hs-abci-examples/nameservice/src/Nameservice/Modules/Nameservice/Messages.hs#L76-L84), but we're not actually using them.

Validation should happen after authentication but before transaction processing.

**Comment by martyall** [comment]
Or in the application level router, whatever makes more sense

**Comment by martyall** [comment]
Maybe we can get a generic implementation of checkTx at the same time, and somehow use that that common step in the application level router.

**Comment by charlescrain** [comment]
Do we want to match the same errors and error codes that the: 
https://github.com/cosmos/cosmos-sdk/blob/master/types/errors.go#L31-L51

**Comment by charlescrain** [comment]
> Or in the application level router, whatever makes more sense

You mean adding the validation [here](https://github.com/f-o-a-m/hs-abci/blob/master/hs-abci-sdk/src/Tendermint/SDK/TxRouter.hs#L55), correct?

> Maybe we can get a generic implementation of checkTx at the same time, and somehow use that that common step in the application level router.

With the generic version would we prevent custom checkTx handlers?

Otherwise, making a `checkTx` function that simply performs validation and throws, then, using that in both the checkTx handler and in the routing could work.

**Comment by martyall** [comment]
> Do we want to match the same errors and error codes 

not necessairily. We can use the sdk error namespace for now, you can find those errors [here](https://github.com/f-o-a-m/hs-abci/blob/master/hs-abci-sdk/src/Tendermint/SDK/Errors.hs#L88-L94). You can make new summand for `MessageValidation` if you want.

**Comment by martyall** [comment]
The cosmos sdk has some notion of an `antehandler`, whose type is something like 

```haskell
type AnteHandler r msg = Member (Error AppError) r => RoutedTx msg -> Sem r ()
```
For example, this is where things like "msg doesn't has not enough fees" or whatever other checks can also come in.

We might eventually want to go there and make that part of the definition of the `Module` type, but if you don't see a clever way for now I think we can just ignore custom handlers and just use message validation.

The type of `Response.CheckTx` makes me think that it's possible to actually run the transaction and rollback the state (note that there is a place for events), so it could be that the only difference between the execution of deliverTx and checkTx is that at checkTx you rollback whatever you just did

**Comment by alexfmpe** [comment]
> The type of Response.CheckTx makes me think that it's possible to actually run the transaction and rollback the state (note that there is a place for events), so it could be that the only difference between the execution of deliverTx and checkTx is that at checkTx you rollback whatever you just did

This is pretty much what happens in Kadenamint (modulo logging).
