### ISSUE TITLE
Make a real CI pipeline for this project

### ISSUE THREAD

**Issue by martyall** [f-o-a-m/kepler#111]
I don't care if it's travis or jenkins. This real CI pipeline should be able to 

1. create branch and merge jobs for each PR
2. build the projects
3. Test all haskell unit tests in all stack projects
4. test the rpc client tests against kvstore app baked into tendermint, see the [README](https://github.com/f-o-a-m/hs-abci/blob/master/hs-tendermint-client/README.md).
5. Run e2e test suite for simple storage against the docker-compose network
6. Run the e2e test suite for nameservice against the docker-compose network

it would be nice if the tests run in parallel.

By docker-compose network, I mean the one in the docker compose file. For example, here is the one for simple storage [docker-compose file](https://github.com/f-o-a-m/hs-abci/blob/master/hs-abci-examples/simple-storage/docker-compose.yaml)

There is a non-functioning dockerfile for each example app. It is an outstanding issue to fix it. I don't care if those e2e tests run the example app in docker, or if they run the app locally against the docker network that it depends on.

NOTE: The tests requiring a tendermint core docker image must wait until they push a 0.32.4 tag to dockerhub, or we must make this image ourselves and host it from our docker repo.

We can continue to run a merge travis job for hlint and stylish when the target branch is master.

Eventually there will probably be a nix component to this, but only if one of the future consultants can do most of the heavy lifting there.

**Comment by iostat** [comment]
>NOTE: The tests requiring a tendermint core docker image must wait until they push a 0.32.4 tag to dockerhub, or we must make this image ourselves and host it from our docker repo.

Is this a hard requirement on patchlevel .4? I see there was an image of `tendermint/tendermint` v0.32.8 pushed yesterday, and there's been a v0.32.3 and v0.32.2 for 3 and 4 months respectively

**Comment by iostat** [comment]
>3. Test all haskell unit tests in all stack projects

Is this covered by `make test-libraries`?
