### ISSUE TITLE
create hs-abci-test-utils package

### ISSUE THREAD

**Issue by martyall** [f-o-a-m/kepler#143]
- [x] factor out all the duplication from nameservice and simple storage utils for managing signing, utils, and expected tx results
- [x] move the client generator from SDK into here, and remove the sdk depenency on the tendermint-client-lib
- [x] move the `FromEvent` class from the `Events` module into here, since again there's no reason the SDK needs to decode events

**Comment by IvantheTricourne** [comment]
> move the FromEvent class from the Events module into here, since again there's no reason the SDK needs to decode events

should we move this test to the test utils test then? https://github.com/f-o-a-m/hs-abci/blob/master/hs-abci-sdk/test/Tendermint/SDK/Test/EventSpec.hs#L17

**Comment by martyall** [comment]
hmm, i guess so
