### ISSUE TITLE
make separate cabal project for iavl grpc

### ISSUE THREAD

**Issue by martyall** [f-o-a-m/kepler#145]
- [x] lib
- [x] tests
- [ ] README

https://github.com/f-o-a-m/hs-trillian example

**Comment by charlescrain** [comment]
still work in progress but here's the branch: https://github.com/f-o-a-m/hs-abci/tree/charles/iavl-client

**Comment by charlescrain** [comment]
Lib is done, working on the tests still.

**Comment by charlescrain** [comment]
https://github.com/f-o-a-m/hs-abci/pull/153
