### ISSUE TITLE
write iavl interpreter for RawStore

### ISSUE THREAD

**Issue by martyall** [f-o-a-m/kepler#173]
There is docker image you can get here to run it as a service https://hub.docker.com/repository/docker/foamspaceorg/iavl

(@blinky3713 fill in details on how to start the container)

```
> docker run -p 8090:8090 -p 8091:8091 foamspace/iavl:latest /iavlserver -db-name DATABASE_NAME -datadir "." -grpc-endpoint "0.0.0.0:8090" -gateway-endpoint "0.0.0.0:8091"

```

We will need to also add this to the compose file(s) for the example apps 

There's gonna be some work to take care of the `Scoped RawStore` stuff. If it's unclear, ask @blinky3713 

What about the cache? In the case of checkTx throw it away, in the case of deliverTx throw it away at the end of processing.

**Comment by charlescrain** [comment]
https://github.com/f-o-a-m/hs-abci/pull/188
