### ISSUE TITLE
Revert travis file for resource conservation

### ISSUE THREAD

**Issue by kejace** [f-o-a-m/kepler#178]
Currently a lot of the tests are running in parallel, but the benefits are low and the cost is high. If not enough parallel processes are payed for with travis, the tests take a really long time because they are effectively duplicated. 

![image](https://user-images.githubusercontent.com/586216/71854940-a7bedb80-30ad-11ea-97ac-7321923542ee.png)

It would be beneficial to put most if not all tests in the same job, sequentially.

**Comment by martyall** [comment]
closed by #195
