### ISSUE TITLE
Move metrics to central location to be used by middleware and app

### ISSUE THREAD

**Issue by martyall** [f-o-a-m/kepler#180]
We want to remove the dependence on the datadog katip cribe and use prometheus for everything. This means that we'll need to move metrics stuff from the SDK into a common place

**Comment by IvantheTricourne** [comment]
You are referring to this scribe? 

https://github.com/f-o-a-m/hs-abci/blob/master/hs-abci-extra/src/Network/ABCI/Server/Middleware/MetricsLogger.hs#L42

Does this mean we're removing the metrics effect?

**Comment by martyall** [comment]
No we're removing the datadog katip scribe from the middleware and using prometheus everywhere

**Comment by martyall** [comment]
The SDK will stay as it is, except that the metrics core types will get moved to a common place
