### ISSUE TITLE
Decide travis build strategy

### ISSUE THREAD

**Issue by kejace** [f-o-a-m/kepler#196]
There's a PR for each of these branches. 

Clearly either of the branches is superior to `master`. Question is, is there any advantage to the staged build in `minimal-travis`? 

|   | master | [minimal-travis](https://github.com/f-o-a-m/hs-abci/pull/184) | [plain-travis](https://github.com/f-o-a-m/hs-abci/pull/195) |
|---|---|---|---|
| number of jobs | 8 |  4 | 2 |
| runtime | 17 min 48 sec |40 min 39 sec | 16 min 23 sec| 
| total | 1 hr 5 sec | 39 min 47 sec | 16 min 23 sec | 
| example | https://travis-ci.com/f-o-a-m/hs-abci/builds/144765942 | https://travis-ci.com/f-o-a-m/hs-abci/builds/144828148 | https://travis-ci.com/f-o-a-m/hs-abci/builds/144831220 |

**Comment by martyall** [comment]
How is there anything to debate? clearly plain-travis wins?

**Comment by kejace** [comment]
I was under the impression that stages helped for tests, but if not, then I agree.

**Comment by martyall** [comment]
closed by #195
