### ISSUE TITLE
Finish docs

### ISSUE THREAD

**Issue by kejace** [f-o-a-m/kepler#204]
Please see https://kejace.github.io/hs-abci/ for live copy

Make PRs against #206 

- [ ] add google analytics (UA-111781922-12)
- [ ] work on haddocks @blinky3713 
- [x] polish docs @charlescrain @IvantheTricourne 
- [x] QA QA QA @charlescrain @IvantheTricourne 
- [x] change all references from `hs-abci` to `kepler` @kejace
- [x] update all licenses to Apache @kejace
- [x] rename on GitHub @kejace 
- [x] publish `gh-pages` in settings @kejace
- [x] point `kepler.dev` to github pages @kejace

**Comment by IvantheTricourne** [comment]
Super slick looking site! I'll just suggest some fixes:

- Links in the [table of contents](https://kejace.github.io/hs-abci/0100-Tutorial.html) are broken (i.e., all the links are pointing to the raw `README`).
- [Types](https://kejace.github.io/hs-abci/0420-Types.html) - typo "like in the definition of `NamespaceError`" should be `NameserviceError`.
- [Logging](https://kejace.github.io/hs-abci/98-Logging.html) 
  - typo "Katip logs are manager by scribes whos job..." should be "whose"
  - the images/screenshots are missing
