### ISSUE TITLE
example app

### ISSUE THREAD

**Issue by martyall** [f-o-a-m/kepler#22]
We need to make a realistic example app, I'm thinking simple storage. Maybe we add the additional requirement that the update count messages contain an integer strictly greater than the current count. It should

- [x] use the logger middleware when it's available
- [x] have a docker file
- [ ] have e2e tests (possibly in PS) that use the docker network
- [ ] have benchmarks
- [x] use a `.proto` file for the messages

**Comment by safareli** [comment]
partially fixed with  #34

**Comment by martyall** [comment]
closing in favor of #40
