### ISSUE TITLE
Consider exporting length function in Array

### ISSUE THREAD

**Issue by UnitylChaos** [f-o-a-m/kepler#258]
Is there a reason this isn't exported ?

https://github.com/f-o-a-m/kepler/blob/a10aa3a84e33709289344c44e03a7cf022a1c2b5/hs-abci-sdk/src/Tendermint/SDK/BaseApp/Store/Array.hs#L232-L238

I can work around this by replicating with a Var in my module, or by using `length <$> Array.toList` but that seems rather inefficient.

**Comment by martyall** [comment]
There is every reason to export this
