### ISSUE TITLE
[Question] Does Kepler only support a linear graph of module dependencies?

### ISSUE THREAD

**Issue by JonathanLorimer** [f-o-a-m/kepler#263]
Judging by `handlersContext` in the [kepler docs](https://kepler.dev/0480-Application.html), and the implementation of `ModuleList` as an h-list I am assuming that only a linear graph of module dependencies is permitted? I am having trouble finding the image, but when reading through the cosmos sdk docs I came across a visualization of the module dependency graph as a dag. Is this a limitation of `kepler` or is it possible to encode a graph in the hlist?

**Comment by martyall** [comment]
I think it already is a dag in some sense. The only restriction is that no module depends on anything before it in the hlist, so for example all of the “BaseEffects” like logging, storage, etc are automatically inserted for you at the end of the hlist so you can use them out of the box. Does that answer your concern ?

I think this usually goes by the name of a topological sorting

**Comment by JonathanLorimer** [comment]
Oh I think I get it now. So for modules `[a, b ,c]` both `a` and `b` can depend on `c`, and only `a` can depend on `b`? I thought that the hlist was saying `a` depends directly on `b` and `b` depends directly on `c`, and that's it.

Thanks for clearing that up, just read about topological sorting and that explains things nicely!

**Comment by martyall** [comment]
yes, I think you have it with that example.
