### ISSUE TITLE
write client library for tendermint core

### ISSUE THREAD

**Issue by martyall** [f-o-a-m/kepler#31]
https://tendermint.com/rpc

**Comment by safareli** [comment]
Would have been great if this was fixed https://github.com/tendermint/tendermint/issues/2419

**Comment by martyall** [comment]
NOTE: ** IN HASKELL**

We need to come up with a list of endpoints / commands sufficient to run e2e tests on an example app.

The websockets part is probably harder, skip for now because there are syncrounous options

**Comment by martyall** [comment]
here's a starting list from https://tendermint.com/rpc/#get-the-list

/abci_info
/health

/abci_query?path=_&data=_&prove=_
/block?height=_
/broadcast_tx_async?tx=_
/broadcast_tx_commit?tx=_
/broadcast_tx_sync?tx=_
/tx?hash=_&prove=_

**Comment by martyall** [comment]
We still need to find an RPC library worth using or rip the tiny client out of hs-web3, let's discuss here
