### ISSUE TITLE
Track `omitempty` issue

### ISSUE THREAD

**Issue by safareli** [f-o-a-m/kepler#46]
Opening this to track `omitempty` issue which would result in parse error if tendermint client we have is used against some go implementation which doens't set all props of types generated from proto files.

https://github.com/tendermint/tendermint/issues/3882

**Comment by martyall** [comment]
@charlescrain do the work around with copy 🍝

**Comment by safareli** [comment]
The tendermint PR was merged and changes are in master

**Comment by IvantheTricourne** [comment]
I tested locally with [tendermint v0.32.4](https://github.com/tendermint/tendermint/commit/ff2308b5f4d13e9f88bfc6a82c4f597c8c73c85d) using the e2e test suite in the `hs-abci-example` app. This seems to alleviate the RPC parse exceptions I was getting earlier:

```
uncaught exception: JsonRpcException        

  ParsingException "key \"code\" not present"
```

The responses with the updated `tendermint` look like this:

```json
{
    "result": {
        "response": {
            "log": "",
            "proof": null,
            "height": "0",
            "value": "AAAAAA==",
            "codespace": "",
            "key": "bDVJOiuTeCnJgVw54jr5ZLyE5UMKfcEExwC7wN4rWeM=",
            "code": 0,
            "index": "0",
            "info": ""
        }
    },
    "jsonrpc": "2.0",
    "id": 1064275510610894592
}
```
