### ISSUE TITLE
Use proper ToJSON/FromJSON instances for Request/Responce

### ISSUE THREAD

**Issue by safareli** [f-o-a-m/kepler#56]
https://github.com/f-o-a-m/hs-abci/issues/44#issuecomment-519429223

**Comment by charlescrain** [comment]
@safareli do you feel we should change all the instances or just the ones that become `Array []`?

**Comment by safareli** [comment]
This is sort of what I mean https://github.com/f-o-a-m/hs-abci/pull/58

But we are lacking fromJSON for `ResponseException` (for completeness)

@blinky3713 is there some other way to write FromJson instance for Request/response?

**Comment by charlescrain** [comment]
Ahh got it, so move the message type stuff into the actual json instances.

I wasn't sure how one does the ResponseException since it can be any of the `t :: MessageType`

**Comment by safareli** [comment]
yeah I'm confused with that too :D will figure something out tomorrow
