### ISSUE TITLE
Write tests for query router

### ISSUE THREAD

**Issue by martyall** [f-o-a-m/kepler#66]
PR #65 has an implementation for a router and uses some machinery to generate getter routes for all `(k,v)` pairs in the store. We just want to make sure this works. There are two things to check:

(1) In the `UserStore` there are to `(k,v,)` types: `(UserKey, User)` and `(DogKey, Dog)`. We want to make sure that we generate the correct routes for `/user/user` and `/user/dog`. This is actually already done.

(2) to test composability, we should check that if we made a `DogStore`, say with the same two `(k,v,)` pairs (so it also stores dogs and humans), then we can issue queries against the correct store automatically. More specifically, if we take

```haskell 

          userServer :: RouteT ("user" :> QueryApi UserStoreContents) IO 
          userServer = allStoreHandlers userStore

          dogServer :: RouteT ("dog" :> QueryApi DogStoreContents) IO 
          dogServer = allStoreHandlers dogStore

          api :: Proxy (("user" :> QueryApi UserStoreContents) :<|> ("dog" :> QueryApi DogStoreContents))
          api = Proxy

          serveRoutes :: Application IO
          serveRoutes = serve api (Proxy :: Proxy IO) (userServer :<|> dogServer)
```

and issue queries against `/user/dog` `/user/user`, `dog/dog`, `dog/user` that they all work

**Comment by charlescrain** [comment]
Rather than putting everything under `/user` I made a `/dog` and `/user` store with 2 routes each.

#65 has the latest and the tests are passing. I think we can consider this closed, unless we want to wait until its all merged into master.

**Comment by charlescrain** [comment]
One thing I noticed while writing the test was that it took me a little to realize that the instance:

```haskell
instance Queryable Lab where
  type Name Lab = "lab"
```
established `lab` as a part of the route. From what I understand this is where we associate the `Lab` type with `<some-store-path>/lab`. I'm pretty ignorant about how everything fits together but if the type of the route could do the association, it could be more straightforward. I.e. :
```haskell
type API = "dog"  :> "lab" :> StoreKey LabKey :>  QueryApi DogStoreContents Lab
```
Again I don't really understand how it all works so this could be super difficult but it reminds me more of how Servant described the API. These are just suggestions I thought of while writing the tests.
