### ISSUE TITLE
Make nameservice example application

### ISSUE THREAD

**Issue by martyall** [f-o-a-m/kepler#77]
We want to make a namespace example application that has parity with the [official cosmos sdk tutorial](https://cosmos.network/docs/tutorial/#tutorial). There are several reasons for doing this:

1. see how dependencies work between modules in the polysemy setting
2. learn more about standard features we need to implement in order to continue working
3. be able to begin work on official documentation pages.

**Comment by martyall** [comment]
> Here are the modules you will need for the nameservice application:

> auth: This module defines accounts and fees and gives access to these functionalities to the rest of your application.
> bank: This module enables the application to create and manage tokens and token balances.
> staking : This module enables the application to have validators that people can delegate to.
> distribution : This module give a functional way to passively distribute rewards between validators and delegators.
> slashing : This module disincentivizes people with value staked in the network, ie. Validators.
> nameservice: This module does not exist yet! It will handle the core logic for the nameservice application you are building. It is the main piece of software you have to work on to build your application.


https://cosmos.network/docs/tutorial/app-design.html#state

**Comment by safareli** [comment]
WIP https://github.com/f-o-a-m/hs-abci/tree/safareli/nameserver

**Comment by martyall** [comment]
It seems like @safareli is working on building the nameserver and bank modules right now

@blinky3713 is working on some of the lower levers where the base app can process messages.
