### ISSUE TITLE
Make a library function to compile BaseApp to IO, or something else that's small

### ISSUE THREAD

**Issue by martyall** [f-o-a-m/kepler#78]
Right now we don't give a standard interpretation of BaseApp to IO, and leave it to the application developer to assemble the various `eval` function in the different modules like [this](https://github.com/f-o-a-m/hs-abci/blob/master/hs-abci-example/app/SimpleStorage/Application.hs#L46-L75). We should provide as much of a standard interpretation as possible.

NOTE: there might be an issue with the logger where we need to leave it un interpreted till the last minute. Still thinking about a way around this...

**Comment by safareli** [comment]
fixed in #83
