### ISSUE TITLE
investigate adding metrics middleware with datadog backend

### ISSUE THREAD

**Issue by martyall** [f-o-a-m/kepler#79]
- [x] make a middleware for server metrics, just measuring response times and counters for messages.

- [ ] investigate making log scribes with ES and Kibana

The end result here is that we can run a node for "a long time" (enough time to accrue data), and collect metrics on it's respnonse times and message counts.

Is there a dockerized setup with a dashboard for viewing metrics? Alternatively there's the "official" dashboard tied to a datadog account. Either way we want to view them.

**Comment by charlescrain** [comment]
I'd be interested in taking this one.

I'm not 100% sure what you mean by `counter for messages`. A count of all state changing messages that come through?

**Comment by charlescrain** [comment]
It seems like all someone needs to do is make a scribe for data dog or elastic search [here is a test for data dog](https://github.com/Soostone/katip/blob/master/katip-datadog/test/Katip/Tests/Scribes/Datadog/TCP.hs#L91) and it seems pretty straight forward.

Are we imagining a wrapper like we do for the [current loggers](https://github.com/f-o-a-m/hs-abci/blob/master/hs-abci-extra/src/Network/ABCI/Server/Middleware/RequestLogger.hs#L53) and the user provides the data dog creds and gets to skip making the logEnvironment?

**Comment by martyall** [comment]
@charlescrain yeah, I that makes sense to me

**Comment by IvantheTricourne** [comment]
Played a bit with @charlescrain branch.

I wrote a simple datadog scribe (as described in charle's comment above), and I currently have logs being collected by a local datadog agent on [my branch](https://github.com/f-o-a-m/hs-abci/tree/carl/middleware-stats-and-scribes). Running `nc -l 10516`, gives you metric logs:

```
{"service":["ABCI"],"severity":"Info","env":"production","thread":"24","host":"Carls-MacBook-Pro.local","pid":51119,"data":{"message_type":"flush","response_time":2.0e-6,"message_count":1209},"message":"","date":"2019-12-04T22:18:55.067498Z","ns":["ABCI","Server"],"loc":null}
{"service":["ABCI"],"severity":"Info","env":"production","thread":"24","host":"Carls-MacBook-Pro.local","pid":51119,"data":{"message_type":"endBlock","response_time":4.0e-6,"message_count":297},"message":"","date":"2019-12-04T22:18:55.067498Z","ns":["ABCI","Server"],"loc":null}
{"service":["ABCI"],"severity":"Info","env":"production","thread":"24","host":"Carls-MacBook-Pro.local","pid":51119,"data":{"message_type":"flush","response_time":1.0e-6,"message_count":1210},"message":"","date":"2019-12-04T22:18:55.067498Z","ns":["ABCI","Server"],"loc":null}
{"service":["ABCI"],"severity":"Info","env":"production","thread":"23","host":"Carls-MacBook-Pro.local","pid":51119,"data":{"message_type":"flush","response_time":6.0e-6,"message_count":1211},"message":"","date":"2019-12-04T22:18:55.07478Z","ns":["ABCI","Server"],"loc":null}
{"service":["ABCI"],"severity":"Info","env":"production","thread":"24","host":"Carls-MacBook-Pro.local","pid":51119,"data":{"message_type":"commit","response_time":4.0e-6,"message_count":297},"message":"","date":"2019-12-04T22:18:55.07478Z","ns":["ABCI","Server"],"loc":null}
{"service":["ABCI"],"severity":"Info","env":"production","thread":"24","host":"Carls-MacBook-Pro.local","pid":51119,"data":{"message_type":"flush","response_time":2.0e-6,"message_count":1212},"message":"","date":"2019-12-04T22:18:55.07478Z","ns":["ABCI","Server"],"loc":null}
```
