### ISSUE TITLE
Make sure we're using the correct protobuf files

### ISSUE THREAD

**Issue by martyall** [f-o-a-m/kepler#8]
We need to double check that we're using the exact version of the types.proto file that we should be, waiting on a reply from Ethan about this one.

**Comment by martyall** [comment]
From Ethan:

> Latest proto file is here: https://github.com/tendermint/tendermint/blob/v0.32.0/abci/types/types.proto

> Though we're about to release v0.32.1 which has a minor non-breaking change (adds a new field to RequestCheckTx).

**Comment by charlescrain** [comment]
### Initial investigation:

* `BlockSizeParam` -> `BlockParam` this is just a simple name change, type is the same
* `KVPair tags` -> `Event event` which is a new type wrapping the `KVPair` this requires making the type for `Event` 

This is probs a good place to pair with @blinky3713 so I can get the experience of defining a type reflecting the protobuf def

**Comment by martyall** [comment]
sounds good, let's figure out a time via rocket chat

**Comment by charlescrain** [comment]
#16

**Comment by charlescrain** [comment]
merged, closing.
