### ISSUE TITLE
Run tendermint-client tests + update Tendermint docker image

### ISSUE THREAD

**Issue by IvantheTricourne** [f-o-a-m/kepler#94]
Currently blocked until Tendermint [v0.32.4 is posted on docker-hub](https://hub.docker.com/r/tendermint/tendermint/tags?page=1&name=0.32.4).

This will allow us to run the [`hs-tendermint-client` tests](https://github.com/f-o-a-m/hs-abci/blob/master/hs-tendermint-client/kv-test/KVStore/Test/KVSpec.hs#L19) from docker.

**Comment by martyall** [comment]
maybe we can use this image? https://hub.docker.com/layers/tendermint/tendermint/v0.32.8/images/sha256-e6713cf882cc21a2c17840ad9bd3a42e84e312b4918880bb9987b593d3a99336

**Comment by martyall** [comment]
closed by #116
