### ISSUE TITLE
Switch protobuf library to awakesecurity/proto3-suite

### ISSUE THREAD

**Issue by martyall** [f-o-a-m/kepler#95]
https://github.com/awakesecurity/proto3-suite

taken from rocketchat:

(1) we still use protofiles for the Network.ABCI.Types.Messages, and this library can still process those
so there's no difference there
(2) You can still do that for every other type that you want, i.e. ones that maybe you didn't define in your app
(3) Currently you need to write protobuf files by hand in order to make tx message types. This requires you to know protobuf well enough to model all your stuff consistently in proto that you eventually want to represent in haskell

**Comment by martyall** [comment]
- [x] integrate proto3-suite into namerservice app
- [x] define protobuf types for the messages and schema directly in haskell, remove old `.proto` files
- [x] replace the .proto files with the generated protofiles from the haskell types / remove the custom `Setup.hs` 

for the wrapper types, by analogy as long as `Cat` and `Dog` have `FromJSON` instance, this works

```
data Foo = Foo 
  { cat :: Cat
  , dog :: Dog
  } deriving Generic

instance FromJSON Foo where
  parseJSON = genericParseJSON defaultOptions
```

See if we can get a similar high level interface

**Comment by IvantheTricourne** [comment]
[Link to the tutorial](https://github.com/awakesecurity/proto3-suite/blob/master/src/Proto3/Suite/Tutorial.hs)

With regards to @blinky3713:

>  See if we can get a similar high level interface

At first glance, it seems that most field types have to use the low level types (e.g. `Word32` and `Int32`, see [here](https://github.com/awakesecurity/proto3-suite/blob/master/src/Proto3/Suite/Tutorial.hs#L70)), with some flexibility around using another proto message type [as a field](https://github.com/awakesecurity/proto3-suite/blob/master/src/Proto3/Suite/Tutorial.hs#L83).

Will look for further options.

**Comment by IvantheTricourne** [comment]
This was also quite useful: [Low level tutorial](https://github.com/awakesecurity/proto3-wire/blob/master/src/Proto3/Wire/Tutorial.hs)

**Comment by IvantheTricourne** [comment]
See here for a running example (complete with encode/decode + `.proto` generation capabilities): 

https://github.com/f-o-a-m/hs-abci/blob/test-proto3/hs-abci-examples/nameservice/src/Nameservice/Protogen.hs
