### ISSUE TITLE
Create protobuf files and type wrappers for nameservice app

### ISSUE THREAD

**Issue by martyall** [f-o-a-m/kepler#97]
- [x] create a protobuf file for the nameservice messages (e.g. `BuyName`)
- [x] create type wrappers for the protobuf messages with normal haskell types (e.g. `MsgBuyName`)
- [x] write parsers (i.e. conversion functions) from the protobuf type to the normal haskell type

- [x] create a protobuf file for the nameservice database types
- [x] create type wrappers for the nameservice database types  with normal haskell types (e.g. `Whois`)
- [x] write parsers (i.e. conversion functions)

**Comment by IvantheTricourne** [comment]
All changes are included in #100.
